version: '3.8'

services:
  app:
    build: .
    container_name: whatsapp_php_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    restart: always

